import type { Metadata } from "next";

import "./globals.css";
import { fredoka_one, gilroy } from "./fonts/font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >

        <div className={`${gilroy.className}  max-w-[1200px] mx-auto`}>
          {children}
        </div>

      </body>
    </html>
  );
}
