import type { Metadata } from "next";

import "./globals.css";
import Image from "next/image";
import { fredoka_one, gilroy } from "./fonts/font";
import Navbar from "./components/Navbar";
import heroMiddleImg from '../../public/assets/hero-middle-plant.png'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Image
          className="absolute top-0 left-0"
          src="/assets/chop/top-left.png"
          alt=""
          width={514}
          height={514}
        />
        <Image
          className="absolute top-0 right-0 -z-10"
          src="/assets/chop/top-right.png"
          alt=""
          width={682}
          height={682}
        />
        <Image
          className="absolute top-[400px] right-[700px] -z-10"
          src="/assets/chop/bottom_hero.png"
          alt=""
          width={514}
          height={514}
        />
        <Image
          className="absolute top-[550px] left-0 -z-10"
          src="/assets/chop/middle-left.png"
          alt=""
          width={514}
          height={514}
        />

        <div className={`${gilroy.className}  max-w-[1200px] mx-auto`}>
          <Navbar />
          <div className='absolute w-[168px] h-[188px] bg-white top-[650px] left-[700px] rounded-4xl [box-shadow:22px_34px_50px_11px_rgba(124,164,23,0.08)]'>
            <Image
              className='absolute -top-16 px-8'
              src={heroMiddleImg}
              alt='fooler tob'
            />
          </div>

          {children}
        </div>

      </body>
    </html>
  );
}
